services:
  awsec2systemkeeper:
    image: ${DOCKER_REGISTRY-}awsec2systemkeeper
    build:
      context: .
      dockerfile: AWSEC2SystemKeeper/Dockerfile
    environment:
      AWS__AccessKey: ${AWS_ACCESS_KEY}
      AWS__SecretKey: ${AWS_SECRET_KEY}
      AWS__Region: ${AWS_REGION}
      AWS__InstanceID: ${AWS_INSTANCE_ID}
    ports:
      - "8080:8080"
    restart: always