name: Deploy Production Environment
on:
  workflow_dispatch:
jobs:
  deploy:
    environment: production
    name: Build and push docker image
    runs-on: aws-01_builder
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: docker compose up
        run: |
             docker-compose up -d -e AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }} \
                        -e AWS_SECRET_KEY=${{ secrets.AWS_ACCESS_SECRET_ID }} \
                        -e AWS_REGION=${{ secrets.AWS_REGION }} \
                        -e AWS_INSTANCE_ID=${{ secrets.AWS_INSTANCE_ID }}
  
